services:
  app:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MERCHANT_UUID=${MERCHANT_UUID}
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: telegram-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - bot-network

  nginx:
    image: nginx:alpine
    container_name: telegram-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - bot-network

volumes:
  redis_data:

networks:
  bot-network:
    driver: bridge
